const GET_COORDINATES_REQUEST = 'GET_COORDINATES_REQUEST';
const GET_COORDINATES_SUCCESS = 'GET_COORDINATES_SUCCESS';
const GET_COORDINATES_FAILURE = 'GET_COORDINATES_FAILURE';

export {
  GET_COORDINATES_REQUEST,
  GET_COORDINATES_SUCCESS,
  GET_COORDINATES_FAILURE
};
